language: r
r:
  - 4.0.2
dist: 
  - xenial

cache:
  packages: true

latex: false
branches:
  only:
    - master

pandoc_version: 2.10.1

repos:
  CRAN: https://cloud.r-project.org

addons:
  apt:
    packages:
      - ghostscript

before_install:
  - Rscript -e 'install.packages("tinytex"); tinytex:::install_prebuilt(); tinytex::tinytex_root()'
  - export PATH=$HOME/bin:$PATH
  - Rscript -e 'tinytex::tlmgr_install(readLines("TeXLive.pkgs"))'

before_script:
  - Rscript -e 'update.packages(lib.loc = .libPaths()[1], ask = FALSE)'
  - chmod +x ./_deploy.sh

script:
  - Rscript -e 'bookdown::render_book("index.Rmd","all")' 

after_success:
  - ./_deploy.sh
